[workspace]
members = [
    "hermit-abi",
    "hermit-sys",
    "benches/netbench",
    "benches/micro",
    "examples/hello_world",
    "examples/httpd",
    "examples/demo",
    "examples/tcp_stream"
]
exclude = ["target", "loader", "libhermit-rs"]
